[env]
CFLAGS = ""
CXXFLAGS = ""

[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=-crt-static"]

[target.x86_64-pc-windows-msvc.env]
CMAKE_POLICY_DEFAULT_CMP0091 = "NEW"
CMAKE_MSVC_RUNTIME_LIBRARY = "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL"
CFLAGS = "/MD"
CXXFLAGS = "/MD"
