[target.x86_64-pc-windows-msvc]
rustflags = []

[target.x86_64-pc-windows-msvc.env]
CMAKE_MSVC_RUNTIME_LIBRARY = "MultiThreadedDLL$<$<CONFIG:Debug>:Debug>"
KNF_STATIC_CRT = "0"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,--allow-multiple-definition"]

[target.aarch64-apple-darwin]
rustflags = "-lc++ -l framework=Accelerate"

[env]
CMAKE_POLICY_VERSION_MINIMUM = "3.5"
