name: Build

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    env:
      SCREENPIPE_TARGET_TRIPLE: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          override: true
          cache: true
          rustflags: ""
      - run: brew unlink pkg-config@0.29.2 || true
      - run: brew install ffmpeg pkg-config
      - run: brew link --overwrite pkg-config
      - run: |
          export PKG_CONFIG_PATH="/usr/local/opt/ffmpeg/lib/pkgconfig:$PKG_CONFIG_PATH"
          export PKG_CONFIG_ALLOW_CROSS=1
          export RUSTFLAGS="-C link-arg=-Wl,-rpath,@executable_path/../lib -C link-arg=-Wl,-rpath,@loader_path/../lib"
          cargo build --release --features metal --target aarch64-apple-darwin
      - run: |
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo 0.0.0)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - run: |
          mkdir -p screenpipe-${{ env.VERSION }}-aarch64-apple-darwin/bin
          cp target/aarch64-apple-darwin/release/screenpipe screenpipe-${{ env.VERSION }}-aarch64-apple-darwin/bin/
          tar -czf screenpipe-${{ env.VERSION }}-aarch64-apple-darwin.tar.gz -C screenpipe-${{ env.VERSION }}-aarch64-apple-darwin .
      - uses: actions/upload-artifact@v4
        with:
          name: screenpipe-macos-aarch64
          path: screenpipe-${{ env.VERSION }}-aarch64-apple-darwin.tar.gz
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
      - uses: oven-sh/setup-bun@v1
      - run: pnpm install
        working-directory: screenpipe-app-tauri
      - run: pnpm run build
        working-directory: screenpipe-app-tauri
      - run: pnpm run tauri build
        working-directory: screenpipe-app-tauri
      - uses: actions/upload-artifact@v4
        with:
          name: screenpipe-app-macos
          path: screenpipe-app-tauri/src-tauri/target/release/bundle

  build-linux:
    runs-on: ubuntu-22.04
    env:
      SCREENPIPE_TARGET_TRIPLE: x86_64-unknown-linux-gnu
      CFLAGS: ""
      CXXFLAGS: ""
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
      - run: |
          sudo apt-get update
          sudo apt-get install -y \
            g++ \
            ffmpeg \
            tesseract-ocr \
            cmake \
            clang \
            libavformat-dev \
            libavfilter-dev \
            libavdevice-dev \
            libssl-dev \
            libtesseract-dev \
            libxdo-dev \
            libsdl2-dev \
            libclang-dev \
            libxtst-dev \
            libx11-dev \
            libxext-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            libgl1-mesa-dev \
            libasound2-dev \
            libpulse-dev \
            curl \
            pkg-config \
            libsqlite3-dev \
            libbz2-dev \
            zlib1g-dev \
            libonig-dev \
            libayatana-appindicator3-dev \
            libsamplerate-dev \
            libwebrtc-audio-processing-dev \
            libgtk-3-dev \
            librsvg2-dev \
            patchelf \
            libdbus-1-dev \
            libfuse2 \
            gstreamer1.0-libav \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-ugly \
            gstreamer1.0-tools \
            libwebkit2gtk-4.1-dev \
            libjavascriptcoregtk-4.1-dev \
            libsoup-3.0-dev \
            libglib2.0-bin \
            libgdk-pixbuf2.0-bin \
            libgtk-3-bin \
            desktop-file-utils
      - run: pkg-config --modversion webkit2gtk-4.1
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
      - uses: oven-sh/setup-bun@v1
      - run: cargo build --release --target x86_64-unknown-linux-gnu
      - run: |
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo 0.0.0)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - run: |
          mkdir -p screenpipe-${{ env.VERSION }}-x86_64-unknown-linux-gnu/bin
          cp target/x86_64-unknown-linux-gnu/release/screenpipe screenpipe-${{ env.VERSION }}-x86_64-unknown-linux-gnu/bin/
          tar -czf screenpipe-${{ env.VERSION }}-x86_64-unknown-linux-gnu.tar.gz -C screenpipe-${{ env.VERSION }}-x86_64-unknown-linux-gnu .
      - uses: actions/upload-artifact@v4
        with:
          name: screenpipe-linux-x86_64
          path: screenpipe-${{ env.VERSION }}-x86_64-unknown-linux-gnu.tar.gz
      - run: pnpm install
        working-directory: screenpipe-app-tauri
      - run: pnpm run build
        working-directory: screenpipe-app-tauri
      - run: pnpm run tauri build -- -vvv
        working-directory: screenpipe-app-tauri
        env:
          APPIMAGE_EXTRACT_AND_RUN: '1'
      - uses: actions/upload-artifact@v4
        with:
          name: screenpipe-app-linux
          path: screenpipe-app-tauri/src-tauri/target/release/bundle

  build-windows:
    runs-on: windows-latest
    env:
      SCREENPIPE_TARGET_TRIPLE: x86_64-pc-windows-msvc
      RUSTFLAGS: "-Ctarget-feature=-crt-static"
      CMAKE_POLICY_DEFAULT_CMP0091: "NEW"
      CMAKE_MSVC_RUNTIME_LIBRARY: "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL"
      CFLAGS: "/MD"
      CXXFLAGS: "/MD"
      CFLAGS_x86_64_pc_windows_msvc: "/MD"
      CXXFLAGS_x86_64_pc_windows_msvc: "/MD"
      KNF_STATIC_CRT: "0"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
      - uses: oven-sh/setup-bun@v1
      - run: |
          $url = "https://7-zip.org/a/7z2301-x64.exe"
          $installer = "7z-installer.exe"
          Invoke-WebRequest -Uri $url -OutFile $installer
          Start-Process -FilePath .\\$installer -Args "/S" -Wait
          Remove-Item $installer
          echo 'C:\\Program Files\\7-Zip' | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh
      - run: cargo clean -p whisper-rs-sys -p knf-rs-sys -p libsamplerate-sys
        shell: pwsh
      - run: |
          echo CMAKE_MSVC_RUNTIME_LIBRARY=$env:CMAKE_MSVC_RUNTIME_LIBRARY
          echo RUSTFLAGS=$env:RUSTFLAGS
        shell: pwsh
      - run: cargo build --release --target x86_64-pc-windows-msvc -vv
        shell: pwsh
      - run: |
          $files = Get-ChildItem "target/x86_64-pc-windows-msvc/release" -Include *.obj,*.lib -Recurse -ErrorAction SilentlyContinue
          $bad = @()
          foreach ($f in $files) {
            $d = & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\bin\Hostx64\x64\dumpbin.exe" /directives $f.FullName 2>$null
            if ($d -match "libcmt" -or $d -match "libcpmt") { $bad += $f.FullName }
          }
          if ($bad.Count -gt 0) {
            Write-Host "Found static CRT directives in:"
            $bad | ForEach-Object { Write-Host $_ }
            exit 1
          }
        shell: pwsh
      - run: |
          $VERSION = git describe --tags --abbrev=0 2>$null
          if ($LASTEXITCODE -ne 0) { $VERSION = "0.0.0"; $LASTEXITCODE = 0 }
          "VERSION=$VERSION" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: pwsh
      - run: |
          $packageDir = "screenpipe-$env:VERSION-x86_64-pc-windows-msvc"
          New-Item -Path "$packageDir/bin" -ItemType Directory -Force
          Copy-Item "target/x86_64-pc-windows-msvc/release/screenpipe.exe" "$packageDir/bin/"
          Copy-Item "target/x86_64-pc-windows-msvc/release/onnxruntime.dll" "$packageDir/bin/" -ErrorAction SilentlyContinue
          7z a "$packageDir.zip" "./$packageDir/*"
        shell: pwsh
      - uses: actions/upload-artifact@v4
        with:
          name: screenpipe-windows
          path: screenpipe-*.zip
      - run: pnpm install
        working-directory: screenpipe-app-tauri
      - run: pnpm run tauri build
        working-directory: screenpipe-app-tauri
      - uses: actions/upload-artifact@v4
        with:
          name: screenpipe-app-windows
          path: screenpipe-app-tauri/src-tauri/target/release/bundle
